apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: andrey-postgres
spec:
  serviceName: andrey-postgres
  replicas: 1
  selector:
    matchLabels:
      app: andrey-postgres
  template:
    metadata:
      labels:
        app: andrey-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:18
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: andrey-postgres-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: andrey-postgres-config
                  key: POSTGRES_USER          
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: andrey-postgres-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: andrey-postgres-data
              mountPath: /var/lib/postgresql
  volumeClaimTemplates:
    - metadata:
        name: andrey-postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi
