apiVersion: v1
kind: Service
metadata:
  name: andrey-postgres
  labels:
    app: andrey-postgres
spec:
  ports:
    - port: 5432
      name: andrey-postgres
  clusterIP: None
  selector:
    app: andrey-postgres
